### ISSUE TITLE
Store og små bokstaver i navn og adresser fra DSF

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/tfk-saksbehandling-skoleskyss#12]
Fra @vavaen I dag følger navnet slik det skrives av søkeren og adressefeltet hentes fra dsf med store bokstaver. Jeg ønsker fornavn og etternavn skrives med stor forbokstav og resten med små. Det samme med adresse.

**Comment by zrrrzzt** [comment]
Navn er ganske uproblematisk @vavaen adresser er litt mer komplisert. På adresser er det jo ikke slik at alle deler **skal** stor bokstav og det er ikke enkelt å finne ut hvilken av delene som skal og ikke.
Jeg foretrekker uansett at vi beholder data slik de blir levert i saksbehandlingsmodulen og at evt endringer gjøres i den delen som legger resultater inn i 360.

Tilordner oppgaven til @maccyber

**Comment by vavaen** [comment]
Jeg forstår det kan være problematisk med adresser, men navnene er jeg fremdeles for å få stor forbokstav. I 360 får vi det riktig inn da det benyttes eksisterende kontakter som er registrert riktig med stor og liten bokstav. Det er spesielt i svarbrevene ut jeg vil ha endringen. I dag går svarbrevene ut slik søkeren skriver navnet sitt, og det er mange varianter.
