### ISSUE TITLE
Endre forbokstaven i Fylkeskommune 

### ISSUE THREAD

**Issue by vavaen** [telemark/tfk-saksbehandling-skoleskyss#13]
Endre til liten forbokstav i fylkeskommune (fra Telemark Fylkeskommune til Telemark fylkeskommune) her:
https://idporten.difi.no/opensso/UI/Login?realm=/norge.no&spEntityID=TFK&service=IDPortenLevel3List&goto=http%3A%2F%2Fidporten.difi.no%2Fopensso%2FSSORedirect%2FmetaAlias%2Fnorge.no%2Fidp2%3FReqID%3Df47696eb4fe54920bc95b2e1fc280a2b%26index%3Dnull%26acsURL%3Dhttps%253A%252F%252Fselvbetjening.t-fk.no%252Fassertionconsumer%26spEntityID%3DTFK%26binding%3Durn%253Aoasis%253Anames%253Atc%253ASAML%253A2.0%253Abindings%253AHTTP-POST

**Comment by zrrrzzt** [comment]
Feil modul. Må fikses hos ID-porten
