### ISSUE TITLE
Pakke ut geocodedAlternativeAddress

### ISSUE THREAD

**Issue by maccyber** [telemark/tfk-saksbehandling-skoleskyss#7]
Trenger å benytte felter i geocodedAlternativeAddress for fara eksport.
Ser gjerne at de pakkes ut på samme måte som _registeredAddress_ f.eks.

``` javascript
alternativeRegisteredAddress : {
street: '',
zip: '',
city: ''
}
```

**Comment by zrrrzzt** [comment]
Behovet for denne faller bort pga https://github.com/telemark/tfk-form-skoleskyss/issues/13
